<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.gigaspaces</groupId>
    <artifactId>schema-evolution-demo</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>
    <modules>
        <module>common</module>
        <module>feeder</module>
        <module>v1-service</module>
        <module>v1-mirror</module>
        <module>v1-temporary-mirror</module>
        <module>v1-final-mirror</module>
        <module>v2-service</module>
        <module>v2-mirror</module>
        <module>v2-load-v1-db</module>
    </modules>
    <properties>
        <gigaspaces.version>17.3.0</gigaspaces.version>
        <kafka.version>2.5.0</kafka.version>
        <mongo.version>3.12.14</mongo.version>
    </properties>

    <repositories>
        <repository>
            <id>org.openspaces</id>
            <url>https://maven-repository.openspaces.org</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.gigaspaces</groupId>
            <artifactId>xap-openspaces</artifactId>
            <version>${gigaspaces.version}</version>
        </dependency>
        <dependency>
            <groupId>com.gigaspaces</groupId>
            <artifactId>xap-admin</artifactId>
            <version>${gigaspaces.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gigaspaces</groupId>
            <artifactId>xap-mongodb</artifactId>
            <version>${gigaspaces.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gigaspaces</groupId>
            <artifactId>xap-kafka</artifactId>
            <version>${gigaspaces.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.2</version>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>3.7.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.2</version>
                <configuration>
                    <outputDirectory>${java.io.tmpdir}/schema-evolution-demo</outputDirectory>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>